version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signer-server
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.datasource.url=jdbc:mysql://database:3307/signer-db
      - spring.datasource.username=root
      - spring.datasource.password=signer123
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=validate
      - spring.jpa.database=mysql
      - server.error.include-message=always

  database:
    image:  mysql:latest
    container_name: signer-database
    environment:
      MYSQL_ROOT_PASSWORD: signer123
      MYSQL_DATABASE: signer-db
    ports:
      - "3307:3306"
